version: "3.7"
services:
  db:
    restart: always
    build:
      context: docker
      dockerfile: database.Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5499:5432
    environment:
      POSTGRES_PASSWORD: postgres
  migrate:
    restart: always
    build:
      context: docker
      dockerfile: migrate.Dockerfile
      args:
        NODEJS_VERSION: ${NODEJS_VERSION}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    volumes:
      - ./:/repo
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/vanderbot
      SHADOW_DATABASE_URL: postgres://postgres:postgres@db/vanderbot_shadow
      ROOT_DATABASE_URL: postgres://postgres:postgres@db/postgres
    depends_on:
      - db
    entrypoint: ["/usr/local/bin/graphile-migrate", "watch"]
    init: true


volumes:
  db: