version: "3.3"
services:
  db:
    restart: always
    build:
      context: docker
      dockerfile: database.Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  graphile-migrate:
    restart: "no"
    build:
      context: docker
      dockerfile: migrate.Dockerfile
      args:
        NODEJS_VERSION: ${NODEJS_VERSION}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    volumes:
      - ./:/repo
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/vanderbot
      SHADOW_DATABASE_URL: postgres://postgres:postgres@db/vanderbot_shadow
      ROOT_DATABASE_URL: postgres://postgres:postgres@db/postgres
    depends_on:
      - db

volumes:
  db: