discord:
  token: ${DISCORD_BOT_TOKEN}
  intent: 32767 # IntentsAll


logging:
  level: debug
  development: true
  encoding: console

fed:
  guilds:
    "417747579489615883":
      deletedMessageLog:
        channel: "1068328877753114694"
        allowDeletion: true
      spotifyLogChannel: "1067758546478956604"
    "1066511028260716575":
      deletedMessageLog:
        channel: "1067758546478956604"
        allowDeletion: true
      spotifyLogChannel: "1067758546478956604"
