discord:
  token: ${DISCORD_BOT_TOKEN}
  intent: 32767 # IntentsAll


logging:
  level: debug
  development: true
  encoding: console

fed:
  guilds:
    "417747579489615883":
      enableDeletedMessageLogging: true
      logChannel: "1068328877753114694"