name: Build

on:
  push:

env:
  GOPRIVATE: "github.com"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: imjasonh/setup-ko@v0.6
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://YOUR_GITHUB_USERNAME:${TOKEN}@github.com".insteadOf "https://github.com"
      - run: go test ./...
      - run: go build ./...
      - run: |-
          mkdir -p cmd/vanderbot/kodata/
          cp cmd/vanderbot/config/* cmd/vanderpot/kodata/
          ko build -P
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)