name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check that migrations are committed.
        run: git diff ${{ github.base_ref }} -- migrations/current.sql || (echo "All migrations must be committed. Run graphile-migrate commit."; false)

